add update and upgrade and wireguard

diff --git a/secure_server b/secure_server
--- a/secure_server
+++ b/secure_server
@@ -1,5 +1,8 @@
 #!/bin/bash
 
+apt update
+apt upgrade
+
 # Funzione per cambiare la password di un utente
 change_password() {
   local username=$1
@@ -11,6 +14,16 @@ change_password() {
   fi
   echo "Password cambiata con successo per l'utente $username"
 }
+
+# Installare WireGuard
+echo "Installazione di WireGuard"
+apt update
+apt install -y wireguard
+if [[ $? -ne 0 ]]; then
+  echo "Errore nell'installazione di WireGuard"
+  exit 1
+fi
+echo "WireGuard installato con successo"
 
 # Cambiare la password di root
 echo "Cambiare la password di root"
